#!/bin/bash

battery=/sys/class/power_supply/BAT0
factor=1000000000000

while true; do
  printf " "
  echo - | awk "{printf \"%.1f\", \
  $(( \
    $(cat $battery/current_now) * \
    $(cat $battery/voltage_now) \
  )) / $factor}" ; echo -ne " W "\\r
  sleep 3
done
